language: go

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

# Use docker
sudo: false

# The latest Groovy should be installed because the Groovy version installed by default at travis is too old.
install:
  - curl -s get.sdkman.io | bash
  - echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
  - source ~/.sdkman/bin/sdkman-init.sh
  - sdk install groovy
  - export GROOVY_HOME=~/.sdkman/candidates/groovy/`ls -1 ~/.sdkman/candidates/groovy | sort -r | grep -v current | head -n 1`

before_script:
  - $GROOVY_HOME/bin/groovy -version
  - go version

script:
  - ./gradlew clean check distLocalBin || ( echo "=============================="; find build/test-results -name "*.xml" | xargs cat ; exit 1 )

cache:
  directories:
    - $HOME/.gradle/
